Cleanup git submodule overkill.  This will fetch the intended version of dependency, not latest (which might not be compaible).

diff --git a/maintainer-tools/configure.in b/maintainer-tools/configure.in
--- a/maintainer-tools/configure.in
+++ b/maintainer-tools/configure.in
@@ -158,26 +158,13 @@ then
 	echo "Using git to fetch cpc-dev-tool-chain from network..."
 	if inside_git_workdir
 	then
-	    echo "We're inside a GIT directory, checking out as submodule."
+	    echo "We're inside a GIT directory. Using git submodule to populate cpc-dev-tool-chain..."
 	    set -xv
-	    git submodule add "$GITHUB_CDTC" || echo >&2 "git submodule add failed, moving along as it may already have been configured."
-	    git submodule init -- cpc-dev-tool-chain || echo >&2 "git submodule init failed, moving along."
-	    git submodule update --init --remote -- cpc-dev-tool-chain || echo >&2 "git submodule init --remote failed, moving along."
-	    git submodule update --init --remote --recursive || echo >&2 "git submodule init --remote --recursive all failed, moving along."
+	    git submodule update --init -- cpc-dev-tool-chain || echo >&2 "git submodule update --init failed, moving along."
 	    set +xv
-
-	    PROBE="cpc-dev-tool-chain/sdcc-project.Makefile"
-	    if ! [[ -r "$PROBE" ]]
-	    then
-		echo "No $PROBE"
-		echo "Using git submodule to populate cpc-dev-tool-chain..."
-		set -xv
-		git submodule update --remote
-		set +xv
-	    fi
 	else
 	    set -xv
-	    echo "Not inside a GIT directory, doing git clone."
+	    echo "Not inside a GIT directory, probably the current project does is not git-base version controller. Doing git clone."
 	    git clone "$GITHUB_CDTC"
 	    set +xv
 	fi
