Allow git submodule add to fail.  The repository may have already been configured.

diff --git a/maintainer-tools/configure.in b/maintainer-tools/configure.in
--- a/maintainer-tools/configure.in
+++ b/maintainer-tools/configure.in
@@ -159,7 +159,7 @@ then
 	if inside_git_workdir
 	then
 	    echo "We're inside a GIT directory, checking out as submodule."
-	    git submodule add "$GITHUB_CDTC"
+	    git submodule add "$GITHUB_CDTC" || echo >&2 "git submodule add failed, moving along as it may already have been configured."
 	else
 	    echo "Not inside a GIT directory, doing git clone."
 	    git clone "$GITHUB_CDTC"
